import type { Metadata } from "next";
import { Inter, Open_Sans } from "next/font/google";
import "./globals.css";
import { StoreProvider } from "@/components/providers/redux.provider";
const inter = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hostify",
  description: "Generated by create next app",
  icons: {
    icon: "/hostify.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <StoreProvider>{children}</StoreProvider>
        </main>
      </body>
    </html>
  );
}
